apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  labels:
    {{- include "workshop-pipelines.labels" . | nindent 4 }}  
type: Opaque
stringData:
  secretToken: MTIzNDU2Nw==
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ci-github
  labels:
    {{- include "workshop-pipelines.labels" . | nindent 4 }}
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          name: gitrepositoryurl
          value: $(body.repository.html_url)
      interceptors:
        - name: verify-github-payload
          params:
            - name: secretRef
              value:
                secretKey: secretToken
                secretName: github-secret
            - name: eventTypes
              value:
                - push
          ref:
            kind: ClusterInterceptor
            name: github
      name: github-push-events-trigger
      template:
        spec:
          params:
            - name: gitrepositoryurl
          resourcetemplates:
            - apiVersion: tekton.dev/v1
              kind: PipelineRun
              metadata:
                generateName: workshop-pipelines-
                labels:
                  tekton.dev/pipeline: workshop-pipelines
                  app: workshop-pipelines
              spec:
                params:
                  - name: GIT_REPO
                    value: $(tt.params.gitrepositoryurl)                
                  - name: IMAGE_NAME
                    value: 'image-registry.openshift-image-registry.svc:5000/maximilianopizarro5-dev/workshop-pipelines'
                  - name: PATH_CONTEXT
                    value: /app
                  - name: MAVEN_IMAGE
                    value: 'registry.redhat.io/ubi8/openjdk-17@sha256:af305e087061cbaa4107ce0b304a1ef987f6b54bae3f75bfd529cfd084cba9b5'
                  - name: APP_JAR_VERSION
                    value: ecommerce-0.0.1-SNAPSHOT.jar
                pipelineRef:
                  name: workshop-pipelines
                taskRunTemplate:
                  serviceAccountName: pipeline
                timeouts:
                  pipeline: 1h0m0s
                workspaces:
                  - name: workspace
                    volumeClaimTemplate:
                      metadata:
                        creationTimestamp: null
                      spec:
                        accessModes:
                          - ReadWriteOnce
                        resources:
                          requests:
                            storage: 4Gi
                        storageClassName: gp2
                        volumeMode: Filesystem
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ci-github
  labels:
    {{- include "workshop-pipelines.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: el-ci-github
    weight: 100
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect      